---
:name: taptranslate
:files:
  - bootstrap.js
  - chrome.manifest
  - icon.png
  - icon64.png
  - install.rdf
  - options.xul
:folders:
  - assets
  - chrome
:compile:
  - bootstrap.coffee
:push_to_device: false
:app_id: org.mozilla.firefox
